### ISSUE TITLE
Gitpod build fails with "Error: Cannot find module 'tobspr-osx-sign'"

### ISSUE THREAD

**Issue by UnsignedArduino** [tobspr/shapez.io#1418]
I was trying to build shapez.io on Gitpod (Using the link in the README) and now it errors out on `yarn run`. Maybe about roughly 6 months ago, it would work just fine and build properly. 

Gitpod task 1:
```
 HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
yarn && gp sync-done boot
}
gitpod /workspace/shapez.io $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn && gp sync-done boot
> }
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.18", while you're on "1.22.17".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 28.85s.
gitpod /workspace/shapez.io $ 
```
Gitpod task 2:
```
 HISTFILE=/workspace/.gitpod/cmd-1 history -r; {
cd gulp
} && {
gp sync-await boot && yarn
} && {
yarn gulp
}
gitpod /workspace/shapez.io $  HISTFILE=/workspace/.gitpod/cmd-1 history -r; {
> cd gulp
> } && {
> gp sync-await boot && yarn
> } && {
> yarn gulp
> }
boot done
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 31.49s.
yarn run v1.22.17
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
Please set SHAPEZ_CLI_APPLE_ID
Please set SHAPEZ_CLI_APPLE_CERT_NAME
Please set SHAPEZ_CLI_GITHUB_USER
Please set SHAPEZ_CLI_GITHUB_TOKEN
Error: Cannot find module 'tobspr-osx-sign'
Require stack:
- /workspace/shapez.io/gulp/standalone.js
- /workspace/shapez.io/gulp/gulpfile.js
- /workspace/shapez.io/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /workspace/shapez.io/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /workspace/shapez.io/gulp/node_modules/gulp-cli/index.js
- /workspace/shapez.io/gulp/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspace/shapez.io/gulp/standalone.js:11:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/workspace/shapez.io/gulp/gulpfile.js:68:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/shapez.io/gulp/standalone.js',
    '/workspace/shapez.io/gulp/gulpfile.js',
    '/workspace/shapez.io/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/workspace/shapez.io/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/workspace/shapez.io/gulp/node_modules/gulp-cli/index.js',
    '/workspace/shapez.io/gulp/node_modules/gulp/bin/gulp.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gitpod /workspace/shapez.io/gulp $ 
```

**Comment by EmeraldBlock** [comment]
the "tobspr-osx-sign" package issue is known, and also Gitpod isn't updated. See quoted fix below:
> in gulp module, there's a lockfile for yarn, find url of "tobspr-osx-sign" and download the archive, extract "package" directory from it, and rename it to "tobspr-osx-sign" and put it into gulp/node_modules

**Comment by mamamia5x** [comment]
I had this error myself, but I think it's because yarn was running on 1.22.17, but it needs 1.22.19.

Running the command `curl --compressed -o- -L https://yarnpkg.com/install.sh | bash` seemed to fix this issue.
