### ISSUE TITLE
Unable to run fresh builds

### ISSUE THREAD

**Issue by PNMarano** [tobspr/shapez.io#1431]
This issue has been present for at least a week. I initially discovered it while trying to use the docker container via the Dockerfile in the source, but also get the same results when following the manual build instructions in the README.md (on Ubuntu-Budgie 22.04). 

In both cases Shapez seems to build correctly. However trying to actually run the built docker image or running the final "yarn gulp" in the manual instructions fails. The issue is Shapez attempts to fetch https://libgdx.badlogicgames.com/ci/nightlies/runnables/runnable-texturepacker.jar at that point which fails for two reasons. The main one is curl has a problem with the site's certificate and therefore aborts the download attempt. The second issue is that even if you ignore the certificate issue, badlogicgames.com is dead, generating 503 errors for any request. The site has been doing this for at least a week now, I don't know when it started.  The only info I've been able to find about badlogicgames.com's status is:
https://www.reddit.com/r/libgdx/comments/v1lgb4/problem_with_the_libgdx_docs_server/
which isn't encouraging.

There are other errors as well, but I suspect they're the result of the missing runnable-texturepacker.jar.

I imagine that site is well outside your control, but it does mean that the Shapez build instructions will completely fail as they currently are.

I'll include the full results of "yarn gulp" for reference below:

yarn run v1.22.18
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
Please set SHAPEZ_CLI_APPLE_ID
Please set SHAPEZ_CLI_APPLE_CERT_NAME
Please set SHAPEZ_CLI_GITHUB_USER
Please set SHAPEZ_CLI_GITHUB_TOKEN
[02:09:07] Using gulpfile /shapez.io/gulp/gulpfile.js
[02:09:07] Starting 'default'...
[02:09:07] Starting 'main.serveDev'...
[02:09:07] Starting 'build.dev'...
[02:09:07] Starting 'utils.cleanup'...
[02:09:07] Starting 'utils.cleanBuildFolder'...
[02:09:07] Finished 'utils.cleanBuildFolder' after 38 ms
[02:09:07] Starting 'utils.cleanImageBuildFolder'...
[02:09:07] Finished 'utils.cleanImageBuildFolder' after 6.16 ms
[02:09:07] Starting 'utils.cleanBuildTempFolder'...
[02:09:07] Finished 'utils.cleanBuildTempFolder' after 5.16 ms
[02:09:07] Finished 'utils.cleanup' after 51 ms
[02:09:07] Starting 'utils.copyAdditionalBuildFiles'...
[02:09:07] Finished 'utils.copyAdditionalBuildFiles' after 10 ms
[02:09:07] Starting 'localConfig.findOrCreate'...
[02:09:07] Finished 'localConfig.findOrCreate' after 867 μs
[02:09:07] Starting 'imgres.buildAtlas'...
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
--2022-06-05 02:09:07--  https://libgdx.badlogicgames.com/ci/nightlies/runnables/runnable-texturepacker.jar
Resolving libgdx.badlogicgames.com (libgdx.badlogicgames.com)... 95.216.8.184
Connecting to libgdx.badlogicgames.com (libgdx.badlogicgames.com)|95.216.8.184|:443... connected.
ERROR: cannot verify libgdx.badlogicgames.com's certificate, issued by 'CN=letsencrypt-nginx-proxy-companion':
  Self-signed certificate encountered.
    ERROR: certificate common name 'letsencrypt-nginx-proxy-companion' doesn't match requested host name 'libgdx.badlogicgames.com'.
To connect to libgdx.badlogicgames.com insecurely, use `--no-check-certificate'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
/bin/sh: 1: Syntax error: "(" unexpected
/bin/sh: 1: certutil.exe: not found
Building atlas failed. Java not found / unsupported version?
[02:09:08] Finished 'imgres.buildAtlas' after 1.04 s
[02:09:08] Starting 'imgres.atlasToJson'...
[02:09:08] 'imgres.atlasToJson' errored after 6.66 ms
[02:09:08] Error: ENOENT: no such file or directory, scandir '/shapez.io/res_built/atlas'
    at readdirSync (fs.js:955:3)
    at Object.convert (/shapez.io/gulp/atlas2json.js:12:22)
    at /shapez.io/gulp/image-resources.js:119:21
    at imgres.atlasToJson (/shapez.io/gulp/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:427:14)
    at runBound (domain.js:440:12)
    at asyncRunner (/shapez.io/gulp/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[02:09:08] 'build.dev' errored after 1.12 s
[02:09:08] 'main.serveDev' errored after 1.12 s
[02:09:08] 'default' errored after 1.12 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by EmeraldBlock** [comment]
is the problem simply the incorrect runnable-texturepacker.jar link?

if so, fixed by #1423

**Comment by smiller171** [comment]
@EmeraldBlock You should try again now that 1423 is merged
