### ISSUE TITLE
Unable to build on Mac

### ISSUE THREAD

**Issue by sumihiro** [tobspr/shapez.io#499]
When I ran `yarn gulp` according to the README, I got the following error and the build did not complete.
The `sfx.mp3` doesn't seem to be there, what should I do?

```
yarn run v1.15.2
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
[10:55:07] Using gulpfile ~/Desktop/shapez.io/gulp/gulpfile.js
[10:55:07] Starting 'default'...
[10:55:07] Starting 'main.serveDev'...
[10:55:07] Starting 'build.dev'...
[10:55:07] Starting 'utils.cleanup'...
[10:55:07] Starting 'utils.cleanBuildFolder'...
[10:55:07] Finished 'utils.cleanBuildFolder' after 35 ms
[10:55:07] Starting 'utils.cleanBuildTempFolder'...
[10:55:07] Finished 'utils.cleanBuildTempFolder' after 4.36 ms
[10:55:07] Finished 'utils.cleanup' after 41 ms
[10:55:07] Starting 'utils.copyAdditionalBuildFiles'...
[10:55:07] Finished 'utils.copyAdditionalBuildFiles' after 3.06 ms
[10:55:07] Starting 'imgres.atlas'...
[10:55:07] Finished 'imgres.atlas' after 100 ms
[10:55:07] Starting 'sounds.dev'...
[10:55:07] Starting 'sounds.buildall'...
[10:55:07] Starting 'sounds.music'...
[10:55:07] Starting 'sounds.sfx'...
[10:55:07] Starting 'sounds.sfxGenerateSprites'...
[ '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/badge_notification.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/destroy_building.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/dialog_error.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/dialog_ok.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/level_complete.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/place_belt.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/place_building.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/ui_click.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/ui_error.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/ui_swish_hide.wav',
  '/Users/me/Desktop/shapez.io/res_raw/sounds/sfx/ui_swish_show.wav' ] undefined
[10:55:07] Plumber found unhandled error:
 Error: gulp-audiosprite: Error adding file undefined
[10:55:07] Finished 'sounds.sfxGenerateSprites' after 389 ms
[10:55:07] Starting 'sounds.sfxOptimize'...
[10:55:07] 'sounds.sfxOptimize' errored after 5.51 ms
[10:55:07] Error: File not found with singular glob: /Users/me/Desktop/shapez.io/res_built/sounds/sfx.mp3 (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:285:20)
    at Glob.emit (events.js:197:13)
    at Glob.EventEmitter.emit (domain.js:481:20)
    at Glob._finish (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:197:8)
    at done (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/me/Desktop/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:764:12)
    at RES (/Users/me/Desktop/shapez.io/gulp/node_modules/inflight/inflight.js:31:16)
    at f (/Users/me/Desktop/shapez.io/gulp/node_modules/once/once.js:25:25)
    at FSReqCallback.oncomplete (fs.js:158:21)
[10:55:07] 'sounds.sfx' errored after 472 ms
[10:55:07] 'sounds.buildall' errored after 473 ms
[10:55:07] 'sounds.dev' errored after 473 ms
[10:55:07] 'build.dev' errored after 617 ms
[10:55:07] 'main.serveDev' errored after 618 ms
[10:55:07] 'default' errored after 620 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by PrestonHager** [comment]
The `sfx.mp3` is part of the LFS files. Try running `git lfs pull` before running yarn, and make sure that `ffmpeg` is in your path.

**Comment by sumihiro** [comment]
I started over again from `git pull origin master`.
I'm at `baf5c83` now.

This time the result of `yarn gulp` is a `Circular dependency detected` error.

```
[07:58:41] Starting 'js.dev.watch'...
[BS] Access URLs:
 ----------------------------
 Local: http://localhost:3005
 ----------------------------
    UI: http://localhost:3001
 ----------------------------
[BS] Serving files from: /Users/me/Desktop/shapez.io/build
[BS] 1 file changed (index.html)
[BS] Reloading Browsers...
[07:58:44] Version: webpack 4.43.0
Built at: 2020-07-29 7:58:44
                             Asset      Size     Chunks                   Chunk Names
781916f24562e3cb4395.worker.js.map  4.06 KiB             [emitted] [dev]  
                         bundle.js  2.45 MiB  bundle.js  [emitted]        bundle.js
                     bundle.js.map  2.36 MiB  bundle.js  [emitted] [dev]  bundle.js
cc02052c77fc61fb31b4.worker.js.map  87.5 KiB             [emitted] [dev]  
Entrypoint bundle.js = bundle.js bundle.js.map

ERROR in Circular dependency detected:
game/building_codes.js -> game/meta_building.js -> game/components/static_map_entity.js -> game/building_codes.js

ERROR in Circular dependency detected:
game/components/static_map_entity.js -> game/building_codes.js -> game/meta_building.js -> game/components/static_map_entity.js

ERROR in Circular dependency detected:
game/meta_building.js -> game/components/static_map_entity.js -> game/building_codes.js -> game/meta_building.js
Child worker:
                                 Asset      Size  Chunks                   Chunk Names
    781916f24562e3cb4395.worker.js.map  4.06 KiB    main  [emitted] [dev]  main
     + 1 hidden asset
    Entrypoint main = 781916f24562e3cb4395.worker.js 781916f24562e3cb4395.worker.js.map
Child worker:
                                 Asset      Size  Chunks                   Chunk Names
    cc02052c77fc61fb31b4.worker.js.map  87.5 KiB    main  [emitted] [dev]  main
     + 1 hidden asset
    Entrypoint main = cc02052c77fc61fb31b4.worker.js cc02052c77fc61fb31b4.worker.js.map
[07:58:44] webpack is watching for changes
[BS] Reloading Browsers... (buffered 4 events)
```

**Comment by nathanskone** [comment]
@sumihiro I built today on Mac OS 10.15.6 without problems, following the readme instructions. I am on commit `baf5c83`.

I also get three `ERROR in Circular dependency detected` messages, but the game plays fine despite those errors.

**Comment by sumihiro** [comment]
@nathanskone Today, I tried again.
After the build, I reloaded the browser a few times and the game launched.
Thanks.

The build message shows an error, but the game seems to work fine.
