### ISSUE TITLE
Cannot successfully build on Ubuntu 20.04

### ISSUE THREAD

**Issue by JohnMackYouTube05** [tobspr/shapez.io#695]
I have followed the instructions exactly on how to build shapez.io, and I can do every command, except when I get to the final step, which was to run ``yarn gulp``, I get error code 1:

Here's what the terminal prints:
```john@john-ubuntu-pc:~/shapezio/shapez.io/gulp$ yarn gulp
yarn run v1.22.5
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
[13:32:26] Using gulpfile ~/shapezio/shapez.io/gulp/gulpfile.js
[13:32:26] Starting 'default'...
[13:32:26] Starting 'main.serveDev'...
[13:32:26] Starting 'build.dev'...
[13:32:26] Starting 'utils.cleanup'...
[13:32:26] Starting 'utils.cleanBuildFolder'...
[13:32:26] Finished 'utils.cleanBuildFolder' after 22 ms
[13:32:26] Starting 'utils.cleanBuildTempFolder'...
[13:32:26] Finished 'utils.cleanBuildTempFolder' after 4.25 ms
[13:32:26] Finished 'utils.cleanup' after 27 ms
[13:32:26] Starting 'utils.copyAdditionalBuildFiles'...
[13:32:26] Finished 'utils.copyAdditionalBuildFiles' after 6.77 ms
[13:32:26] Starting 'imgres.atlas'...
[13:32:26] Finished 'imgres.atlas' after 36 ms
[13:32:26] Starting 'sounds.dev'...
[13:32:26] Starting 'sounds.buildall'...
[13:32:26] Starting 'sounds.music'...
[13:32:26] Starting 'sounds.sfx'...
[13:32:26] Starting 'sounds.sfxGenerateSprites'...
[ '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/badge_notification.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/destroy_building.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/dialog_error.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/dialog_ok.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/level_complete.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/place_belt.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/place_building.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/ui_click.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/ui_error.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/ui_swish_hide.wav',
  '/home/john/shapezio/shapez.io/res_raw/sounds/sfx/ui_swish_show.wav' ] undefined
[13:32:26] Plumber found unhandled error:
 Error: gulp-audiosprite: Error adding file undefined
[13:32:26] Finished 'sounds.sfxGenerateSprites' after 258 ms
[13:32:26] Starting 'sounds.sfxOptimize'...
[13:32:26] 'sounds.sfxOptimize' errored after 6.67 ms
[13:32:26] Error: File not found with singular glob: /home/john/shapezio/shapez.io/res_built/sounds/sfx.mp3 (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:197:8)
    at done (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:688:12)
    at /home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/john/shapezio/shapez.io/gulp/node_modules/glob-stream/node_modules/glob/glob.js:764:12)
    at RES (/home/john/shapezio/shapez.io/gulp/node_modules/inflight/inflight.js:31:16)
    at f (/home/john/shapezio/shapez.io/gulp/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:21)
[13:32:26] 'sounds.sfx' errored after 318 ms
[13:32:26] 'sounds.buildall' errored after 318 ms
[13:32:26] 'sounds.dev' errored after 319 ms
[13:32:26] 'build.dev' errored after 389 ms
[13:32:26] 'main.serveDev' errored after 390 ms
[13:32:26] 'default' errored after 393 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Could someone help me figure out why I cannot successfully build this game on Ubuntu 20.04? That would be amazing, 

Thank you.

**Comment by daanbreur** [comment]
You are missing sound assets.
So do `git lfs pull` or if that doesnt work download them here
https://discord.com/channels/706121159405731910/708586448240115723/758385547261116426

**Comment by JohnMackYouTube05** [comment]
I downloaded the sounds assets from discord, thank you.

**Comment by daanbreur** [comment]
Your welcome!
