### ISSUE TITLE
Trouble building on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Jungolbuk** [tobspr/shapez.io#856]
When running `yarn gulp` in the gulp directory I keep getting this error
yarn run v1.22.10
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
Please set SHAPEZ_CLI_APPLE_ID
Please set SHAPEZ_CLI_APPLE_CERT_NAME
Please set SHAPEZ_CLI_GITHUB_USER
Please set SHAPEZ_CLI_GITHUB_TOKEN
Error: Cannot find module '@octokit/rest'
Require stack:
- /home/me/shapez.io/gulp/release-uploader.js
- /home/me/shapez.io/gulp/gulpfile.js
- /home/me/shapez.io/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js
- /home/me/shapez.io/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /home/me/shapez.io/gulp/node_modules/gulp-cli/index.js
- /home/me/shapez.io/gulp/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/me/shapez.io/gulp/release-uploader.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/me/shapez.io/gulp/gulpfile.js:68:25)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/me/shapez.io/gulp/release-uploader.js',
    '/home/me/shapez.io/gulp/gulpfile.js',
    '/home/me/shapez.io/gulp/node_modules/gulp-cli/lib/shared/require-or-import.js',
    '/home/me/shapez.io/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/home/me/shapez.io/gulp/node_modules/gulp-cli/index.js',
    '/home/me/shapez.io/gulp/node_modules/gulp/bin/gulp.js'
  ]
}
error Command failed with exit code 1.

I have tried reinstalling node and yarn using npm but I haven't been able to fix this error.  I am a bit inexperienced when it comes to programming altogether, so I might've made an error when following the readme, but I believe that I followed it exactly.

**Comment by LeopoldTal** [comment]
Did you run `yarn` in the root folder **and** in `gulp/`?

**Comment by Hyperion-21** [comment]
Why was this closed?

**Comment by DoubleU47** [comment]
Also would like to know why this was closed. I have the same issue despite doing `yarn` in both folders. (root and gulp)
